"""add connector_type mcp_server data_type to alert_rules

Revision ID: 0d3a775bcb95
Revises: 7435d0d0770e
Create Date: 2026-03-08 05:05:45.459528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d3a775bcb95'
down_revision: Union[str, Sequence[str], None] = '7435d0d0770e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connector_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='legacy'))
        batch_op.add_column(sa.Column('mcp_server', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_column('data_type')
        batch_op.drop_column('mcp_server')
        batch_op.drop_column('connector_type')

    # ### end Alembic commands ###
