"""DBHub MCP Server integration — TOML config generation + command building."""

from __future__ import annotations

import tempfile
from pathlib import Path

from loguru import logger

from order_guard.mcp.models import MCPServerConfig


def build_dbhub_toml(config: MCPServerConfig) -> str:
    """Generate dbhub.toml content from MCPServerConfig.

    Each database in config.databases becomes a [[sources]] entry.
    Security settings (readonly, max_rows) become [[tools]] entries.
    """
    lines: list[str] = ["# Auto-generated by OrderGuard"]

    for db in config.databases:
        lines.append("")
        lines.append("[[sources]]")
        lines.append(f'id = "{db.alias}"')
        lines.append(f'dsn = "{db.dsn}"')
        if db.query_timeout is not None:
            lines.append(f"query_timeout = {db.query_timeout}")

    # Configure execute_sql tool per source with security settings
    for db in config.databases:
        lines.append("")
        lines.append("[[tools]]")
        lines.append('name = "execute_sql"')
        lines.append(f'source = "{db.alias}"')
        lines.append(f"readonly = {str(config.security.readonly).lower()}")
        lines.append(f"max_rows = {config.security.max_rows}")

    return "\n".join(lines) + "\n"


def write_dbhub_toml(config: MCPServerConfig, base_dir: Path | None = None) -> Path:
    """Write dbhub.toml to a temp file and return its path.

    If base_dir is given, write to base_dir/dbhub-{name}.toml instead.
    """
    content = build_dbhub_toml(config)

    if base_dir is not None:
        base_dir.mkdir(parents=True, exist_ok=True)
        toml_path = base_dir / f"dbhub-{config.name}.toml"
        toml_path.write_text(content, encoding="utf-8")
    else:
        # Use a persistent temp file (deleted on process exit)
        tmp = tempfile.NamedTemporaryFile(
            prefix=f"dbhub-{config.name}-",
            suffix=".toml",
            mode="w",
            delete=False,
            encoding="utf-8",
        )
        tmp.write(content)
        tmp.close()
        toml_path = Path(tmp.name)

    logger.debug("DBHub TOML written: {}", toml_path)
    return toml_path


def build_dbhub_command(config: MCPServerConfig, toml_path: Path) -> tuple[str, list[str]]:
    """Build the npx command + args to start DBHub with the generated TOML.

    Returns (command, args) suitable for MCPServerConfig.
    """
    command = "npx"
    args = [
        "-y",
        "@bytebase/dbhub",
        f"--config={toml_path}",
        "--transport",
        "stdio",
    ]
    return command, args


def prepare_dbhub_config(config: MCPServerConfig) -> MCPServerConfig:
    """Resolve a DBHub config into a runnable MCPServerConfig.

    Generates the TOML config file and returns a new config with
    command/args set for stdio transport.
    """
    if not config.databases:
        raise ValueError(
            f"DBHub server '{config.name}' requires at least one database in 'databases'"
        )

    toml_path = write_dbhub_toml(config)
    command, args = build_dbhub_command(config, toml_path)

    # Return a new config with command/args populated
    return MCPServerConfig(
        name=config.name,
        type="dbhub",
        transport="stdio",
        command=command,
        args=args,
        env=config.env,
        enabled=config.enabled,
        databases=config.databases,
        security=config.security,
    )
